#!/usr/bin/env python3
"""Render article figures from checked numerical outputs.

Run from any working directory. No field values or numerical outcomes are
recomputed here: those are read from results generated by run_simulations.py.
The chemistry and remedy panels are evidence summaries, not measurements.
"""
from __future__ import annotations

import argparse
import csv
import hashlib
import json
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib import animation, colors
from matplotlib.patches import FancyArrowPatch, FancyBboxPatch
import numpy as np
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / "assets"
RESULTS = ROOT / "results"
CHARCOAL = "#202A30"
MUTED = "#59656D"
PALE = "#E2E7EA"
BLUE = "#1F658C"
ORANGE = "#B56330"


def apply_style():
    plt.rcParams.update({
        "font.family": "DejaVu Sans", "font.size": 11,
        "text.color": CHARCOAL, "axes.labelcolor": CHARCOAL,
        "axes.edgecolor": MUTED, "xtick.color": MUTED, "ytick.color": MUTED,
        "axes.spines.top": False, "axes.spines.right": False,
        "figure.facecolor": "white", "axes.facecolor": "white",
        "savefig.facecolor": "white", "svg.fonttype": "none",
        "mathtext.fontset": "dejavusans", "axes.titleweight": "medium",
    })


def save_pair(fig, stem):
    ASSETS.mkdir(exist_ok=True)
    for extension in ("png", "svg"):
        fig.savefig(ASSETS / f"{stem}.{extension}", dpi=210,
                    facecolor="white", bbox_inches="tight", pad_inches=.16)


def header(fig, title, subtitle, x=.055, y=.95):
    fig.text(x, y, title, fontsize=22, weight="bold", ha="left", va="top")
    fig.text(x, y-.068, subtitle, fontsize=11.5, color=MUTED,
             ha="left", va="top")


def chemistry():
    """Verified pathway, using catalysts on arrows rather than as products."""
    fig = plt.figure(figsize=(13.4, 4.2))
    ax = fig.add_axes([.015, .06, .97, .68])
    ax.set(xlim=(0, 1), ylim=(0, 1))
    ax.axis("off")
    header(fig, "From cut tissue to reflex tears",
           "Cutting brings the precursor isoalliin into contact with alliinase.",
           y=.95)
    centres = [.115, .375, .635, .885]
    labels = ["Isoalliin", "1-Propenesulfenic\nacid",
              "syn-Propanethial\nS-oxide", "Eye irritation\nand reflex tears"]
    details = ["Sulfur precursor", "Reaction intermediate",
               "Lachrymatory factor", "Response to exposure"]
    widths = [.190, .190, .190, .190]
    for i, (x, label, detail, width) in enumerate(zip(centres, labels, details, widths)):
        rect = FancyBboxPatch((x-width/2, .33), width, .28,
                              boxstyle="round,pad=0.015,rounding_size=0.012",
                              facecolor="#F4F7F9" if i == 2 else "white",
                              edgecolor=BLUE if i == 2 else PALE,
                              linewidth=1.4)
        ax.add_patch(rect)
        ax.text(x, .47, label, ha="center", va="center", fontsize=12.8,
                weight="medium", linespacing=1.35)
        ax.text(x, .205, detail, ha="center", va="center", fontsize=10,
                color=MUTED)
    catalysts = ["alliinase", "LF synthase", "transport\nthrough air"]
    for i in range(3):
        xa = centres[i]+widths[i]/2+.017
        xb = centres[i+1]-widths[i+1]/2-.017
        ax.add_patch(FancyArrowPatch((xa, .47), (xb, .47), arrowstyle="-|>",
                                    mutation_scale=13, color=CHARCOAL,
                                    linewidth=1.2))
        ax.text((xa+xb)/2, .72, catalysts[i], ha="center", va="center",
                fontsize=10.5, linespacing=1.35,
                color=BLUE if i < 2 else MUTED)
    ax.plot([.035, .745], [.90, .90], color=PALE, lw=1)
    ax.text(.035, .925, "CHEMISTRY IN DAMAGED TISSUE", fontsize=9,
            color=MUTED, va="bottom", weight="bold")
    fig.text(.055, .045,
             "Enzyme names label the reactions. Coproducts and competing reactions omitted. Schematic; molecular structures and distances not shown.",
             fontsize=9.1, color=MUTED)
    save_pair(fig, "figure_02_chemistry")
    plt.close(fig)


def load_csv(path):
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def remedies():
    """Qualitative evidence table approved by the research review."""
    rows = [
        ("Well-sealed\ngoggles", "Irritant entry\naround the eyes", "Physical barrier", "Fit and leaks matter; no controlled\nonion efficacy estimate located."),
        ("Air directed\naway from the face", "Transport from\nsource to face", "Transport reasoning\nand conditional model", "Benefit depends on direction,\nposition and room airflow."),
        ("Sharp blade,\ngentle cuts", "Mechanical\ndroplet release", "Controlled cutting\nstudy", "Fewer droplets do not establish\nless vapour or fewer tears."),
        ("Chilled onion", "Chemistry, emission\nand tissue mechanics", "Net effect uncertain", "No reliable estimate of tearing\nover the whole task located."),
        ("Water at the cut", "Direct contact\nand interception", "Plausible mechanism;\nefficacy unestablished", "Direct contact differs from a\nnearby bowl or wet towel."),
        ("Verified low-LF\nvariety", "Production of\nlachrymatory factor", "Measured LF reduction;\nsensory support", "Specific lines; sensory evidence\nwas not from a chopping trial."),
        ("Root kept intact", "Damage to\nparticular tissues", "Prevention\nunestablished", "No controlled lachrymatory-factor\nor tear comparison located."),
        ("Bread or\nchewing gum", "Claimed household\nremedies", "Reliable prevention\nunestablished", "No adequate peer-reviewed support;\nlimited patent evidence for gum."),
    ]
    fig = plt.figure(figsize=(14.2, 9.2))
    ax = fig.add_axes([.042, .09, .918, .735])
    ax.set(xlim=(0, 1), ylim=(0, 1))
    ax.axis("off")
    header(fig, "Which methods have support?",
           "Evidence concerns different outcomes; it does not supply a universal ranking.",
           x=.055, y=.967)
    col_x = [.008, .226, .467, .702]
    col_labels = ["METHOD", "WHAT IT CAN CHANGE", "EVIDENCE", "LIMIT"]
    for x, lab in zip(col_x, col_labels):
        ax.text(x, .964, lab, fontsize=10.2, weight="bold", color=MUTED,
                ha="left", va="center")
    ax.plot([0, 1], [.925, .925], lw=1.3, color=CHARCOAL)
    h = .109
    for i, row in enumerate(rows):
        y_top = .925-i*h
        y_mid = y_top-h/2
        if i % 2 == 0:
            ax.add_patch(plt.Rectangle((0, y_top-h), 1, h, color="#F5F7F8",
                                       linewidth=0, zorder=0))
        for j, (x, cell) in enumerate(zip(col_x, row)):
            ax.text(x, y_mid, cell, fontsize=11.0 if j < 3 else 10.4,
                    weight="medium" if j == 0 else "normal",
                    color=BLUE if j == 2 else CHARCOAL,
                    ha="left", va="center", linespacing=1.43)
        ax.plot([0, 1], [y_top-h, y_top-h], lw=.65, color=PALE)
    fig.text(.055, .063,
             "LF = lachrymatory factor. Evidence status follows the documented search; an unlocated trial is not proof of no effect.",
             fontsize=10.1, color=MUTED)
    fig.text(.055, .031,
             "Study sources, search limits and method-specific qualifications are provided in the article and claim ledger.",
             fontsize=9.7, color=MUTED)
    save_pair(fig, "figure_05_remedies")
    plt.close(fig)


SCENARIO_LABELS = {
    "no_mean_drift": "No mean drift",
    "toward": "Toward the observation point",
    "away": "Away from the observation point",
    "transverse": "Across the source-to-observer line",
}


def grouped_histories():
    rows = load_csv(RESULTS / "time_histories.csv")
    groups = {}
    for row in rows:
        key = (row["source_id"], row["scenario_id"])
        groups.setdefault(key, []).append(row)
    return {key: {col: np.array([float(row[col]) for row in series])
                  for col in ("time_s", "emission_rate_per_s",
                              "concentration_per_m3", "cumulative_exposure_s_per_m3")}
            for key, series in groups.items()}


def air_motion_table():
    """Render the four published values directly from the checked summary."""
    summary = json.loads((RESULTS / "summary.json").read_text())
    records = {(r["source_id"], r["scenario_id"]): r for r in summary["results"]}
    rows = [
        ("No mean drift", "no_mean_drift", ".2f"),
        ("Toward the observation point", "toward", ".2f"),
        ("Perpendicular to the source–observer line", "transverse", ".3f"),
        ("Away from the observation point", "away", ".4f"),
    ]
    fig = plt.figure(figsize=(14, 5.25))
    ax = fig.add_axes([0, 0, 1, 1])
    ax.set(xlim=(0, 1), ylim=(0, 1))
    ax.axis("off")
    left, right, top, height = .052, .949, .775, .175
    ax.text(left, .91, "PRESCRIBED AIR MOTION", fontsize=19.2,
            weight="bold", color=MUTED, va="center")
    ax.text(.705, .918, r"$E_{120}/M$", fontsize=21, color=MUTED, va="center")
    ax.text(.705, .866, "in seconds per cubic metre", fontsize=14.3,
            color=MUTED, va="center")
    ax.plot([left, right], [top, top], lw=1.6, color=CHARCOAL)
    values = []
    for i, (label, scenario, precision) in enumerate(rows):
        y_top = top - i * height
        y = y_top - height / 2
        if i % 2 == 0:
            ax.add_patch(plt.Rectangle((left, y_top-height), right-left, height,
                                      facecolor="#F2F4F5", edgecolor="none"))
        value = format(records["fast", scenario]["exposure_120s_s_per_m3"], precision)
        ax.text(left+.015, y, label, fontsize=19.8, color=CHARCOAL, va="center")
        ax.text(right-.018, y, value, fontsize=22, color=BLUE, ha="right", va="center")
        ax.plot([left, right], [y_top-height, y_top-height], lw=.8, color=PALE)
        values.append({"label":label, "scenario_id":scenario, "display_value":value})
    ASSETS.mkdir(exist_ok=True)
    for suffix in ("png", "svg"):
        fig.savefig(ASSETS / f"table_01_air_motion.{suffix}", dpi=160, facecolor="white")
    plt.close(fig)
    (ASSETS / "table_01_air_motion.json").write_text(json.dumps({
        "source_file":"results/summary.json",
        "source_sha256":hashlib.sha256((RESULTS/"summary.json").read_bytes()).hexdigest(),
        "source_id":"fast", "quantity":"exposure_120s_s_per_m3",
        "unit":"s/m^3", "rows":values,
        "output_sha256":{suffix:hashlib.sha256((ASSETS/f"table_01_air_motion.{suffix}").read_bytes()).hexdigest()
                         for suffix in ("png", "svg")},
    }, indent=2)+"\n", encoding="utf-8")


def profiles():
    """Compare timing at fixed total release and fixed toward transport."""
    histories = grouped_histories()
    summary_rows = load_csv(RESULTS / "summary.csv")
    summary = next(r for r in summary_rows
                   if r["source_id"] == "fast" and r["scenario_id"] == "toward")
    infinite_key = next(k for k in summary if "infinite" in k and "exposure" in k)
    infinite_exposure = float(summary[infinite_key])
    config = json.loads((ROOT / "config" / "model_config.json").read_text())
    fig, axes = plt.subplots(1, 3, figsize=(13.8, 5.7))
    fig.subplots_adjust(left=.075, right=.982, bottom=.255, top=.68, wspace=.35)
    header(fig, "A lower peak can leave total exposure unchanged",
           f"Two hypothetical sources with equal total release; unchanged flow toward the observer at {config['flow_speed_m_s']:.2f} m/s.",
           x=.055, y=.966)
    keys = ("emission_rate_per_s", "concentration_per_m3", "cumulative_exposure_s_per_m3")
    panel_titles = ("A  Release from the source", "B  Concentration near the eye", "C  Accumulated exposure")
    ylabels = ("Release / total amount (s⁻¹)", "Concentration / amount (m⁻³)",
               "Exposure / common infinite-time limit")
    for source_id, colour, style, label in [
            ("fast", BLUE, "-", "Shorter release"),
            ("slow", ORANGE, "--", "Longer release")]:
        data = histories[(source_id, "toward")]
        rates = config["sources"][source_id]
        tau_p = 1 / rates["k_production_per_s"]
        tau_e = 1 / rates["k_release_per_s"]
        for j, (ax, key) in enumerate(zip(axes, keys)):
            scale = infinite_exposure if j == 2 else 1.
            ax.plot(data["time_s"], data[key]/scale, color=colour, linestyle=style,
                    linewidth=2.2, label=f"{label} (time constants {tau_p:g}, {tau_e:g} s)")
    for ax, title, ylabel in zip(axes, panel_titles, ylabels):
        ax.set_title(title, fontsize=11, loc="left", pad=12)
        ax.set_ylabel(ylabel, fontsize=10)
        ax.set_xlabel("Time after source activation (s)", fontsize=9.4, labelpad=9)
        ax.set_xlim(0, config["history"]["end_time_s"])
        ax.set_ylim(bottom=0)
        ax.set_xticks([0, 30, 60, 90, 120])
        ax.tick_params(labelsize=9)
        ax.grid(axis="y", color=PALE, linewidth=.65, zorder=0)
        ax.set_axisbelow(True)
    axes[0].set_yticks([0, .04, .08, .12])
    axes[0].set_ylim(0, max(float(histories[("fast", "toward")][keys[0]].max()),
                          float(histories[("slow", "toward")][keys[0]].max()))*1.08)
    axes[2].axhline(1, color=MUTED, linestyle=(0, (2, 3)), linewidth=1)
    axes[2].set_ylim(0, 1.06)
    axes[2].set_yticks([0, .25, .5, .75, 1])
    handles, labels = axes[0].get_legend_handles_labels()
    fig.legend(handles, labels, loc="upper left", bbox_to_anchor=(.055, .832),
               frameon=False, ncol=2, fontsize=10.7, handlelength=3.4, columnspacing=3)
    fig.text(.055, .102,
             "Both sources eventually emit the same amount. In this fixed linear model, integration over all future time gives the same exposure.",
             fontsize=10, color=MUTED)
    fig.text(.055, .056,
             "Release timing is imposed, not calibrated to chilling or knife technique. Curves end at 120 s; the dotted line is the common infinite-time limit.",
             fontsize=9.6, color=MUTED)
    save_pair(fig, "figure_04_release_exposure")
    plt.close(fig)


def transport(animate=True):
    """Display true 3D fields in a common planar slice on one fixed scale."""
    with np.load(RESULTS / "animation_fields.npz", allow_pickle=False) as data:
        d = {key: data[key] for key in data.files}
    times = d["times_s"]
    x, z = d["x_m"], d["z_m"]
    fields = d["concentration_per_m3"]
    ids = [str(s) for s in d["scenario_ids"]]
    source = d["source_position_m"]
    obs = d["observation_position_m"]
    velocity = d["velocity_m_s"]
    if not np.isclose(obs[1], 0):
        raise ValueError("Observation centre must lie in the displayed y=0 plane.")
    if not np.all(fields >= 0):
        raise ValueError("Cannot plot negative concentration.")
    vmax = 10 ** np.ceil(np.log10(float(fields.max())))
    vmin = vmax * 1e-5
    norm = colors.LogNorm(vmin=vmin, vmax=vmax)
    cmap = colors.LinearSegmentedColormap.from_list(
        "onion_blue", ["#F8FBFD", "#E0EAF2", "#9DC5DD", "#5795BA", BLUE, "#133B53"])
    cmap.set_under("white")
    cmap.set_bad("white")

    fig, axes = plt.subplots(2, 2, figsize=(11.5, 10.2))
    fig.subplots_adjust(left=.075, right=.815, bottom=.12, top=.80,
                        hspace=.33, wspace=.23)
    header(fig, "The same source, four routes through air",
           "Calculated 3D concentration in the y = 0 plane; one fixed colour scale for all panels and times.",
           x=.075, y=.97)
    clock = fig.text(.075, .841, "", fontsize=13, weight="medium", color=BLUE)
    fig.text(.435, .841, "■ Source     ○ Observation centre", fontsize=11, color=CHARCOAL)
    images = []
    for i, ax in enumerate(axes.flat):
        dx, dz = x[1]-x[0], z[1]-z[0]
        im = ax.imshow(np.ma.masked_less(fields[i, 0], vmin),
                       extent=(x[0]-dx/2, x[-1]+dx/2, z[0]-dz/2, z[-1]+dz/2), origin="lower",
                       cmap=cmap, norm=norm, interpolation="nearest", aspect="equal")
        images.append(im)
        ax.plot(source[0], source[2], marker="s", ms=5, color=CHARCOAL, zorder=4)
        ax.plot(obs[0], obs[2], marker="o", ms=9, markerfacecolor="none",
                markeredgecolor=CHARCOAL, markeredgewidth=1.6, zorder=5)
        ax.set_title(SCENARIO_LABELS.get(ids[i], ids[i]), fontsize=11.5, loc="left", pad=9)
        ax.set_xlabel("x (m)", fontsize=10)
        ax.set_ylabel("z (m)", fontsize=10)
        ax.set_xlim(x[0], x[-1])
        ax.set_ylim(z[0], z[-1])
        ax.set_xticks([-.5, 0, .5, 1.0])
        ax.set_yticks([-.5, 0, .5, 1.0])
        ax.tick_params(labelsize=9)
        ax.spines[["top", "right"]].set_visible(True)
        for spine in ax.spines.values():
            spine.set_color(PALE)
        if ids[i] in ("toward", "away"):
            direction = velocity[i, [0, 2]]
            direction = direction / np.linalg.norm(direction)
            start = np.array([-.53, -.35])
            ax.annotate("", xy=start+.24*direction, xytext=start,
                        arrowprops=dict(arrowstyle="-|>", lw=1.5, color=CHARCOAL))
            ax.text(-.72, -.73, f"Uniform drift: {np.linalg.norm(velocity[i]):.2f} m/s",
                    fontsize=8.7, color=MUTED)
        elif ids[i] == "transverse":
            ax.text(-.70, -.53, "⊗", fontsize=21, color=CHARCOAL)
            ax.text(-.48, -.52, "Perpendicular (+y)", fontsize=8.6, va="center", color=MUTED)
            ax.text(-.70, -.73, f"Uniform drift: {np.linalg.norm(velocity[i]):.2f} m/s",
                    fontsize=8.7, color=MUTED)
        else:
            ax.text(-.70, -.66, "Mixing without mean drift", fontsize=8.8, color=MUTED)
    cax = fig.add_axes([.864, .24, .022, .41])
    cb = fig.colorbar(images[0], cax=cax,
                      ticks=np.logspace(np.log10(vmin), np.log10(vmax), 6))
    cb.ax.tick_params(labelsize=9)
    cb.set_label("Concentration / total released amount (m⁻³)\nLogarithmic scale", fontsize=10, labelpad=12)
    cb.outline.set_edgecolor(PALE)
    fig.text(.075, .058,
             "Illustrative effective mixing and prescribed flow in unbounded air. Fields are not measurements of onion vapour or tearing.",
             fontsize=9.0, color=MUTED)
    fig.text(.075, .033,
             "The point marks the centre of a Gaussian observation average. No wall, cutting board, body plume or room circulation is modelled.",
             fontsize=9.0, color=MUTED)

    def update(frame):
        for i, im in enumerate(images):
            im.set_data(np.ma.masked_less(fields[i, frame], vmin))
        clock.set_text(f"Time after source activation: {times[frame]:.0f} s")
        return [*images, clock]

    # A data-derived snapshot at the nearest stored frame to peak exposure in
    # the toward-flow case. This does not change any colour normalization.
    history = grouped_histories()[("fast", "toward")]
    peak_time = history["time_s"][np.argmax(history["concentration_per_m3"])]
    static_frame = int(np.argmin(np.abs(times-peak_time)))
    update(static_frame)
    save_pair(fig, "animation_01_transport_static")
    metadata = {"frame_count": len(times), "physical_duration_s": float(times[-1]),
                "snapshot_time_s": float(times[static_frame]),
                "colour_scale": "logarithmic; common across every panel and frame",
                "colour_min_per_m3": float(vmin), "colour_max_per_m3": float(vmax),
                "below_colour_min": "shown as white", "displayed_plane": "y = 0 m",
                "scenario_order": ids}
    if animate:
        fps = 6
        frames = [0] * 3 + list(range(len(times))) + [len(times)-1] * 6
        anim = animation.FuncAnimation(fig, update, frames=frames, interval=1000/fps,
                                       blit=False, repeat=True)
        anim.save(ASSETS / "animation_01_transport.mp4",
                  writer=animation.FFMpegWriter(fps=fps, codec="libx264", bitrate=1800,
                    extra_args=["-pix_fmt", "yuv420p", "-movflags", "+faststart",
                                "-vf", "pad=ceil(iw/2)*2:ceil(ih/2)*2:color=white"]), dpi=100)
        anim.save(ASSETS / "animation_01_transport.gif",
                  writer=animation.PillowWriter(fps=fps), dpi=100)
        with Image.open(ASSETS / "animation_01_transport.gif") as gif:
            duration_ms = sum((gif.seek(i) or gif.info.get("duration", 0))
                              for i in range(gif.n_frames))
            metadata.update({"mp4_frames_per_second": fps,
                             "mp4_frame_count": len(frames),
                             "mp4_nominal_duration_s": len(frames)/fps,
                             "gif_unique_frames": gif.n_frames,
                             "gif_duration_ms": duration_ms,
                             "gif_dimensions_px": list(gif.size),
                             "timing_note": "GIF centisecond timing differs slightly from MP4; the clock always shows physical time.",
                             "extra_hold_frames": {"opening": 3, "closing": 6}})
    metadata["input_files_sha256"] = {
        str(path.relative_to(ROOT)): hashlib.sha256(path.read_bytes()).hexdigest()
        for path in [RESULTS/"animation_fields.npz", RESULTS/"time_histories.csv",
                     RESULTS/"summary.csv", ROOT/"config"/"model_config.json"]}
    (ASSETS / "visual_metadata.json").write_text(json.dumps(metadata, indent=2)+"\n", encoding="utf-8")
    plt.close(fig)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--only", choices=("all", "chemistry", "transport", "profiles", "remedies", "table"),
                        default="all")
    parser.add_argument("--no-animation", action="store_true")
    args = parser.parse_args()
    apply_style()
    if args.only in ("all", "chemistry"):
        chemistry()
    if args.only in ("all", "remedies"):
        remedies()
    if args.only in ("all", "profiles"):
        profiles()
    if args.only in ("all", "table"):
        air_motion_table()
    if args.only in ("all", "transport"):
        transport(animate=not args.no_animation)
    sources_path = ASSETS / "asset_sources.json"
    if sources_path.exists():
        sources = json.loads(sources_path.read_text())
        for record in sources["images"]:
            if record["origin"] == "original project asset":
                record["sha256"] = hashlib.sha256((ROOT/record["path"]).read_bytes()).hexdigest()
        sources_path.write_text(json.dumps(sources, indent=2)+"\n", encoding="utf-8")


if __name__ == "__main__":
    main()
